name: check
on:
  push:

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

concurrency: ci-${{ github.ref }}-${{ github.workflow }}

permissions:
  contents: read

env:
  TF_CLI_ARGS: -no-color

jobs:
  terraform:
    name: Terraform
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: 'false'
      - name: Install linter
        uses: terraform-linters/setup-tflint@ae78205cfffec9e8d93fd2b3115c7e9d3166d4b6 # v5.0.0
        with:
          tflint_version: v0.53.0
      - name: Load linter plugin cache
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
      - name: Install linter plugins
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }} # to avoid rate limits on plugin installation
      - name: Lint module
        run: make lint

      - name: Install Terraform
        uses: 'hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd' # v3.1.2
        with:
          terraform_version: '1.11.4'

      - name: Initialize Terraform
        run: make init

      - name: Check formatting
        run: make fmt-check

      - name: Check documentation
        run: make docs-check

      - name: Validate configuration
        run: make validate

  github-actions-workflows:

    name: GitHub Actions
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    permissions:
      security-events: write # allow zizmor to upload security audit results
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: 'false'

      - name: Lint workflows
        uses: raven-actions/actionlint@a9f1bde40b4c45b3f92816d3834ec9e719895a0e #

      - name: Audit workflows
        uses: zizmorcore/zizmor-action@f52a838cfabf134edcbaa7c8b3677dde20045018 # v0.1.1

  renovate:
    name: Renovate
    timeout-minutes: 30
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: 'false'

      - name: Validate config
        run: npx --yes --package renovate -- renovate-config-validator --strict renovate.json5

