name: check
on:
  push:

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

concurrency: ci-${{ github.ref }}-${{ github.workflow }}

permissions:
  contents: read

env:
  TF_CLI_ARGS: -no-color

jobs:
  lint:
    name: Lint configuration
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: 'false'
      - name: Install linter
        uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6 # v4.1.1
        with:
          tflint_version: v0.53.0
      - name: Load linter plugin cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
      - name: Install linter plugins
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }} # to avoid rate limits on plugin installation
      - name: Lint module
        run: make lint

  validate:
    name: Validate configuration
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: 'false'
      - name: Install Terraform
        uses: 'hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd' # v3.1.2
        with:
          terraform_version: '1.11.4'
      - name: Initialize Terraform
        run: make init
      - name: Validate configuration
        run: make validate

  formatting:
    name: Check formatting
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: 'false'
      - name: Install Terraform
        uses: 'hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd' # v3.1.2
        with:
          terraform_version: '1.11.4'
      - name: Check formatting
        run: make fmt-check

  docs:
    name: Check documentation
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: 'false'
      - name: Check if module documentation is up to date
        run: make docs-check
