name: check
on:
  push:

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

concurrency: ci-${{ github.ref }}-${{ github.workflow }}

permissions:
  contents: read

env:
  TF_CLI_ARGS: -no-color

jobs:
  terraform:
    name: Terraform
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: 'false'

      - name: Install tools
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          version: 2025.8.7
          install: true # run mise install
          cache: true

      - name: Load tflint plugin cache
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Lint module
        run: make lint

      - name: Initialize module
        run: make init

      - name: Check formatting
        run: make fmt-check

      - name: Check documentation
        run: make docs-check

      - name: Validate configuration
        run: make validate

  github-actions-workflows:

    name: GitHub Actions
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    permissions:
      security-events: write # allow zizmor to upload security audit results
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: 'false'

      - name: lint workflows
        uses: raven-actions/actionlint@a9f1bde40b4c45b3f92816d3834ec9e719895a0e #

      - name: audit workflows
        uses: zizmorcore/zizmor-action@5ca5fc7a4779c5263a3ffa0e1f693009994446d1 # v0.1.2

  release:
    name: Create GitHub release
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    needs: [terraform, github-actions-workflows]

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: conditionally semantic release
        run: make release
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
